### ISSUE TITLE
[META] Definición de roadmap

### ISSUE THREAD

**Issue by fjaguero** [mozillahispano/One-Mozilla-blog#1]
La idea comentada con @voylinux es generar un theme limpio y en el que se pueda trabajar en el futuro. Reemplazaría al theme actual, moviendo los archivos compartidos del header y footer para quitar dependencías. Aquí podemos comentar roadmap y definir los pasos a seguir.

General:
- [ ] Setup de entorno de desarrollo
- [ ] TBD

Backend:
- [ ] TBD

Frontend:
- [ ] Comprobación de Home (menús, estilos, etc.)
- [ ] Comprobación de posts (estilos)
- [ ] Aplicar marca de Mozilla Hispano
- [ ] TBD

**Comment by fjaguero** [comment]
Comments welcome @voylinux

**Comment by fjaguero** [comment]
Notificar también a @mozillahispano/tecnico que comenzamos con esto

**Comment by fjaguero** [comment]
¿Sigue teniendo sentido esto? @mozillahispano/tecnico

**Comment by nukeador** [comment]
No se, era un proyecto que queríais sacar adelante. @voylinux ?

**Comment by nukeador** [comment]
En todo caso, aquí está el nuevo branding

https://mozilla.ninja/
